# Specify a base image
FROM node:alpine

WORKDIR '/app'

# Install some dependencies
# separate the copy section, speed up when rebuild docker image
COPY ./package.json ./
RUN npm install
COPY ./ ./

# Default command
CMD ["npm", "run", "dev"]
